data:
  raw_NQ: data/raw/NQ.csv
  raw_ES: data/raw/ES.csv
  raw_EMD: data/raw/EMD.csv
  raw_YM: data/raw/YM.csv
indicators: # setting the parameters used to compute the indexes
  rsi_period: 2
  hurst_window: 20
  short_composite_rsi: 2
  long_composite_rsi: 24
entry_thresholds: # setting the interval for RSI
  rsi_low: 10.0
  rsi_high: 20.0
  hurst_threshold: 50.0
exit_thresholds: # setting the exit criteria
  max_profitable_closes: 5
  max_bars_in_trade: 11
  composite_rsi_threshold: 0.5
ablation: # setting ablation boolean values to make testing and parameters isolation robust
  use_rsi: true
  use_hurst: true
  use_composite_rsi: true
  use_time_exit: true
  use_RSI_exit: true
  use_take_profit: true
transaction_costs:
  round_trip_point_drag: 0.50  # Total points (slippage + commission) to subtract per trade
